apiVersion: v1
kind: Service
metadata:
  name: granite-3-2-8b-instruct-epp
spec:
  selector:
    inferencepool: granite-3-2-8b-instruct-epp
  ports:
  - name: grpc-ext-proc
    port: 9002
    protocol: TCP
    targetPort: 9002
  - name: http-metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  type: ClusterIP
