apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceObjective
metadata:
  name: food-review
spec:
  priority: 0
  poolRef:
    group: inference.networking.k8s.io
    name: granite-3-2-8b-instruct-epp
