apiVersion: apps/v1
kind: Deployment
metadata:
  name: granite-3-2-8b-instruct
spec:
  replicas: 1
  selector:
    matchLabels:
      llm-d.ai/model: "granite-3-2-8b-instruct"
      llm-d.ai/inferenceServing: "true"
  template:
    metadata:
      labels:
        llm-d.ai/model: "granite-3-2-8b-instruct"
        llm-d.ai/inferenceServing: "true"
    spec:
      containers:
      - args:
        - --model
        - granite/granite-3-2-8b-instruct
        - --port
        - "8000"
        - --inter-token-latency
        - "50" # in milliseconds
        - --inter-token-latency-std-dev
        - "5" # in milliseconds
        - --time-to-first-token
        - "100" # in milliseconds
        - --time-to-first-token-std-dev
        - "10" # in milliseconds
        image: ghcr.io/llm-d/llm-d-inference-sim:v0.5.1
        imagePullPolicy: IfNotPresent
        name: vllm-sim
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
             path: /health
             port: 8000
          initialDelaySeconds: 10 # simulate vllm startup time (optimized)
          periodSeconds: 5
