apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: granite-3-2-8b-instruct
  labels:
    release: prometheus # match the prometheus release label
spec:
  selector:
    matchLabels:
      llm-d.ai/model: "granite-3-2-8b-instruct"
      llm-d.ai/inferenceServing: "true"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - port: http
    path: "/metrics"
    interval: "5s"
